name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout doc
        uses: actions/checkout@v2

      - name: azion-site actions trigger
        run: |
             curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/aziontech/azion-site/dispatches --data '{"event_type": "repository_dispatch", "client_payload": {"unit": false,"integration": true}}'
